# docker-compose.yml
version: '3.9'
 
services:
 
  # The API
  api:
    build: ./api
    container_name: my_api
    restart: unless-stopped
    ports:
      - "3000:3000"          # host:container
    environment:
      DB_HOST:     db         # service name = hostname
      DB_USER:     ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME:     ${POSTGRES_DB}
      DB_PORT:     5432
    depends_on:
      db:
        condition: service_healthy   # wait for DB ready (you will need a database before your backend)
    networks: # making sure the database and api are talking to each other (in docker they are stored inside different containers, need to build a virtual connection between them)
      - backend
 
  # The Database
  db:
    image: postgres:15-alpine
    container_name: my_db
    restart: unless-stopped
    environment:
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:       ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data   # persist DB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend
 
# Volumes
volumes:
  pgdata:
 
# Networks (telling how networking is done)
networks:
  backend:
    driver: bridge
